### ISSUE TITLE
DB Query with Hiera dictionary lookup

### ISSUE THREAD

**Issue by hokadiri** [dalen/puppet-puppetdbquery#35]
When we have a dictionary in heira like:
varnish_pool:
  port: '8080'
  servers::_nodequery:
    query: 'Class[Varnish]'
    fact: 'hostname'

and we do a hiera lookup for "varnish_pool", response i get is:
{"port" => "8080",
 "servers::_nodequery"=>
  {"query"=>
    "Class[Varnish]",
   "fact"=>"hostname"}}
The puppet DB query inside a hash does not resolve.

**Comment by vaijab** [comment]
I am hitting the same issue unfortunately.

**Comment by avkvl** [comment]
And me

**Comment by dalen** [comment]
hmm, yeah, need to look into a fix for this. A workaround if you are using hiera 1.3+ is to do something like this (the key `varnish_pool::servers` can be anything you like):

```
varnish_pool:
  port: '8080'
  servers: "%{hiera('varnish_pool::servers')}"

varnish_pool::servers::_nodequery:
  query: 'Class[Varnish]'
  fact: 'hostname'
```

This should work as the second lookup is a regular query lookup then.
