### ISSUE TITLE
In hiera backend, add ability to use "deep" _nodequery

### ISSUE THREAD

**Issue by vincentbernat** [dalen/puppet-puppetdbquery#84]
Hey!

It would be convenient if the hiera backend was able to substitute a node query when returning a structure from hiera. For example, if we have this:

```yaml
something:
  sources::_nodequery: "Class[...]"
```

It would be convient if the hiera backend was able to return:

```ruby
{ "something" => { "sources" => [ "host1", "host2" ] } }
```

**Comment by gregsaram** [comment]
+1

**Comment by gregsaram** [comment]
I am happy to give it a try but I would need a couple guidelines before I start writing this...
It looks like this can be done by editing the lookup function in puppetdb_backend.rb. I am not sure how to make sure this will retrun the whole hash and run the puppetdb query only for the inner deep key which contain the  "_noquery" ...

```
"profile::elasticsearch::config":
  bootstrap.mlockall: true
  cluster:
    name: usersearch
  discovery:
    zen.minimum_master_nodes: 2
    zen.ping.multicast.enabled: false
    zen.ping.unicast.hosts::_nodequery: ['ec2_tag_role=usmaster', 'ipaddress']
  index:
    search.slowlog.threshold.fetch.debug: 500ms
    search.slowlog.threshold.fetch.info: 800ms
    search.slowlog.threshold.fetch.trace: 200ms
    search.slowlog.threshold.fetch.warn: 1s
    search.slowlog.threshold.query.debug: 2s
    search.slowlog.threshold.query.info: 5s
    search.slowlog.threshold.query.trace: 500ms
    search.slowlog.threshold.query.warn: 10s
  node:
    data: false
    master: true
    name: "%{::hostname}"
```

**Comment by gregsaram** [comment]
Actually we don't need this feature because we can just interpolate the hiera function and let the magic happen:
```  
"profile::elasticsearch::masternodes::_nodequery": ['ec2_tag_role=usmaster', 'ipaddress']

"profile::elasticsearch::config":
  bootstrap.mlockall: true
  cluster:
    name: usersearch
  discovery:
    zen.minimum_master_nodes: 2
    zen.ping.multicast.enabled: false
    zen.ping.unicast.hosts: "%{hiera('profile::elasticsearch::masternodes')}"
  index:
    search.slowlog.threshold.fetch.debug: 500ms
    search.slowlog.threshold.fetch.info: 800ms
    search.slowlog.threshold.fetch.trace: 200ms
    search.slowlog.threshold.fetch.warn: 1s
    search.slowlog.threshold.query.debug: 2s
    search.slowlog.threshold.query.info: 5s
    search.slowlog.threshold.query.trace: 500ms
    search.slowlog.threshold.query.warn: 10s
  node:
    data: true
    master: false
    name: "%{::hostname}"
```

Amazing!
